### ISSUE TITLE
Negative throttle

### ISSUE THREAD

**Issue by jevnik** [sug44/FPV_Drone_forAC#3]
Hi,

I love your mod. Its an awesome project. Just one issue. when using xbox controller, by pulling left analog stick down i get negative acceleration. Like props can spin backwards. Is there a seting i am missing to make throttle from 0-1. 0 can be either on left stick in middle or down. I could play either way. Maybe because xbox analog is springed its better to place 0 in middle. Like it is now. But how to set it up so when i pull down throtle stays 0 and doesnt got to -1? 

If this is a missing feature/bug, I am willing to contribute to your code

**Comment by sug44** [comment]
There is a "3D Mode" checkbox in the Input tab that you can uncheck to make the motors spin only one way. I intentionaly made 3D mode to be on by default because most of the people will be using controllers with centering springs
